version: '3.8'

services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/sueta.db
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-test_token}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:8080/webhook}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-test_key}
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
