version: '3.8'

services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://root:example@mongo:27017
      - MONGO_DATABASE=sueta
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-test_token}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:8080/webhook}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-test_key}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
